export const config = {
  personal: {
    name: "Ezra",
    lastName: "Brilliant",
    fullName: "Ezra Brilliant",
    title: "Business Information Systems Student",
    subtitle: "Mobile App Developer",
    description:
      "Building innovative digital solutions that bridge technology and business through mobile apps and data-driven systems.",
    location: "Surabaya, Indonesia",
    email: "ezrakonterliem@gmail.com",
    phone: "+62-8788-456-7890",
    avatar: "/avatar.jpg",
    resume: "/resume.pdf",
  },

  social: {
    github: "https://github.com/ezrabrilliant",
    linkedin: "https://linkedin.com/in/ezrabrilliant",
    instagram: "https://instagram.com/ezrabrilliant",
  },

  navigation: [
    { name: "Home", href: "#home" },
    { name: "About", href: "#about" },
    { name: "Skills", href: "#skills" },
    { name: "Projects", href: "#projects" },
    { name: "Experience", href: "#experience" },
    { name: "Contact", href: "#contact" },
  ],

  about: {
    introduction:
      "Business Information Systems student at Petra Christian University specializing in Business Intelligence and Mobile Development. Experienced with data analytics, business process optimization, and modern development technologies.",
    highlights: [
      "Enhanced analytical and technical skills through the Bangkit Academy 2024 Mobile Development Path, completing industry-aligned training and certifications.",
      "Seeking to drive digital transformation through business intelligence solutions and data-driven mobile applications.",
    ],
    stats: [
      { label: "Projects", value: "15+" },
      { label: "Technologies", value: "20+" },
      { label: "Learning Hours", value: "500+" },
      { label: "GitHub Commits", value: "1000+" },
    ],
  },

  experience: [
    {
      id: 1,
      title: "Full-Stack Developer (Final-Year Thesis)",
      company: "POS Monosuko — Restaurant POS & Inventory System",
      type: "Thesis Project",
      location: "Surabaya, Indonesia",
      startDate: "2025-09",
      endDate: "2026-06",
      description:
        "Solo developer of an installable-PWA restaurant POS, owning the project end-to-end from design to deployment on a self-managed Ubuntu VPS.",
      technologies: [
        "React",
        "TypeScript",
        "Node.js",
        "Express.js",
        "Prisma",
        "MySQL",
        "Ubuntu VPS",
      ],
      achievements: [
        "Owned it end-to-end: order management (split / merge / void billing), daily portion-stock auto-deduction with low-stock alerts, RBAC across Owner / Cashier / Waiter, and an owner analytics dashboard",
        "Designed the REST API and MySQL schema (Prisma ORM) with role-aware secured endpoints, deployed on a self-managed Ubuntu VPS",
        "Validated with formal UAT (73/73 cases passed) and SUS 75.8 (Good); cut total transaction time by 41% and split-bill queue time by 48.6%",
      ],
    },
    {
      id: 2,
      title: "AI Bot Developer & Maintainer",
      company: "Ezra Bot — AI Discord Community Bot",
      type: "Production Project",
      location: "Remote",
      startDate: "2023-01",
      endDate: "2026-07",
      description:
        "Built and operate a 24/7 production AI bot serving a 1,000+ member community with a hybrid Gemini + GPT-4o engine and RAG long-term memory.",
      technologies: [
        "Node.js",
        "Discord.js",
        "Gemini API",
        "GPT-4o",
        "ChromaDB",
        "MongoDB",
        "Docker",
      ],
      achievements: [
        "Built a hybrid Gemini + GPT-4o engine with RAG-based long-term memory (ChromaDB vector embeddings) so it answers from real community knowledge",
        "Migrated from a local PC to a Dockerized 24/7 cloud architecture on an Ubuntu VPS, keeping it reliable at ~$0.5–1/month",
        "Serves a 1,000+ member community continuously in production",
      ],
    },
    {
      id: 3,
      title: "Solo Full-Stack Developer",
      company: "GTID (gtid.pro) — Community Market Platform",
      type: "Solo Project",
      location: "Remote",
      startDate: "2025-06",
      endDate: "2026-07",
      description:
        "Owned the whole stack of a community web platform solo — from data pipeline and a custom binary parser to a Dockerized VPS deployment.",
      technologies: [
        "Next.js",
        "React",
        "Tailwind CSS",
        "Node.js",
        "MongoDB",
        "Discord API",
        "Docker",
        "Nginx",
      ],
      achievements: [
        "Built a price tracker with historical charts, fuzzy search across 16,088 game items parsed from a binary data file, and real-time Discord status",
        "Shipped a public API (api.gtid.pro) with caching and rate limiting, plus the full data pipeline (scrape, clean, aggregate to MongoDB)",
        "Dockerized deployment on a VPS with Nginx + systemd, serving ~2,600 unique visitors and ~14,500 requests/day",
      ],
    },
    {
      id: 4,
      title: "Roblox Game Programmer",
      company: "Petak Umpet - Roblox Multiplayer Game",
      type: "Game Dev (Collab)",
      location: "Remote",
      startDate: "2026-01",
      endDate: "2026-06",
      description:
        "Sole programmer for a Roblox hide-and-seek game, owning all game logic and collaborating with the project lead / 3D & art asset creator.",
      technologies: ["Roblox Studio", "Luau"],
      achievements: [
        "Owned all game logic: core loop (hider / seeker selection, timers, win / lose conditions), responsive UI, and player ↔ environment interaction",
        "Turned a static PDF design concept into a live, loop integrating 3D and UI assets",
        "Grew to 3.1M+ visits and 2.6K peak concurrent players",
      ],
    },
    {
      id: 5,
      title: "E-commerce Bot Developer & Payment Integration Specialist",
      company: "Orbit Store - Auto Store Discord Bot",
      type: "Entrepreneurial Project",
      location: "Remote",
      startDate: "2024-07",
      endDate: "2025-04",
      description:
        "Developed and deployed a production-ready Discord e-commerce bot with real QRIS payment integration serving hundreds of active customers.",
      technologies: [
        "Discord.js",
        "Node.js",
        "Midtrans API",
        "QRIS",
        "Express.js",
        "MongoDB",
      ],
      achievements: [
        "Built commercial Discord bot processing real monetary transactions with hundreds of active users",
        "Integrated enterprise-level QRIS payment system with Midtrans API",
        "Processed 2,700+ orders from 370+ unique buyers using data chunking for efficient order processing",
        "Implemented secure webhook validation and real-time payment verification",
      ],
    },
    {
      id: 6,
      title: "Mobile Development Graduate",
      company: "Bangkit Academy by Google, Tokopedia, Gojek & Traveloka",
      type: "Top Graduate",
      location: "Remote",
      startDate: "2024-09",
      endDate: "2025-01",
      description:
        "Graduated as top cohort from intensive mobile development program focused on Android development, Flutter, UI/UX design, and mobile app architecture.",
      technologies: [
        "Android",
        "Kotlin",
        "Flutter",
        "Firebase",
        "UI/UX Design",
      ],
      achievements: [
        "Graduated as top student in the cohort",
        "Completed comprehensive mobile development curriculum with distinction",
        "Led team projects using agile methodologies",
      ],
    },
  ],

  education: [
    {
      id: 1,
      institution: "Bangkit Academy",
      degree: "Mobile Development Learning Path",
      field: "Mobile Development",
      startDate: "2024-09",
      endDate: "2025-01",
      location: "Remote",
      gpa: "Top Graduate",
      description:
        "Intensive program by Google, Tokopedia, Gojek, and Traveloka focusing on mobile development and modern app architecture.",
    },
    {
      id: 2,
      institution: "Petra Christian University",
      degree: "Bachelor of Business Information Systems",
      field: "Business Intelligence",
      startDate: "2022-09",
      endDate: "2026-06",
      gpa: "3.14/4.0",
      location: "Surabaya, Indonesia",
      description:
        "Focused on business information systems, business intelligence, data analytics, and digital business transformation.",
    },
  ],

  projects: [
    {
      id: 1,
      title: "POS Monosuko",
      description:
        "Restaurant POS & inventory system built as my final-year thesis — order management with split / merge / void billing, daily portion-stock auto-deduction with low-stock alerts, role-based access, and blind-count cash settlement. Installable PWA on a self-managed VPS. Validated with UAT (73/73 passed) and SUS 75.8; cut transaction time by 41%.",
      image: "/projects/POSMonosuko.png",
      technologies: [
        "React",
        "TypeScript",
        "Node.js",
        "Express.js",
        "Prisma",
        "MySQL",
        "Tailwind CSS",
        "Ubuntu VPS",
      ],
      github: "https://github.com/ezrabrilliant/Skripsi-POS-Restaurant",
      demo: "https://monosuko.my.id",
      status: "completed" as const,
      date: "2026",
    },
    {
      id: 2,
      title: "GTID (gtid.pro)",
      description:
        "Community market platform for Growtopia Indonesia — price tracker with historical charts, fuzzy search across 16,088 game items parsed from a binary data file, live Discord status, and a public API (api.gtid.pro) with caching & rate limiting. Serves ~2,600 unique visitors and ~14,500 requests/day.",
      image: "/projects/GTID.png",
      technologies: [
        "Next.js",
        "React",
        "Tailwind CSS",
        "Node.js",
        "MongoDB",
        "Discord API",
        "Docker",
        "Nginx",
      ],
      github: "",
      demo: "https://gtid.pro",
      status: "completed" as const,
      date: "2026",
    },
    {
      id: 3,
      title: "Petak Umpet",
      description:
        "Roblox multiplayer hide-and-seek game — sole programmer owning all game logic: core loop (hider / seeker selection, timers, win / lose conditions), responsive UI, and end-to-end player ↔ environment interaction. Grew to 3.1M+ visits and 2.6K peak concurrent players.",
      image: "/projects/PetakUmpet.png",
      technologies: ["Roblox Studio", "Luau"],
      github: "",
      demo: "https://www.roblox.com/games/91179701802837/Petak-Umpet",
      status: "completed" as const,
      date: "2026",
    },
    {
      id: 4,
      title: "Ezra Bot",
      description:
        "24/7 production AI Discord bot for a 1,000+ member community — hybrid Gemini + GPT-4o engine with RAG-based long-term memory (ChromaDB vector embeddings) so it answers from real community knowledge. Dockerized on an Ubuntu VPS, running at ~$0.5–1/month.",
      image: "/projects/GPT.png",
      technologies: [
        "Node.js",
        "Discord.js",
        "Gemini API",
        "GPT-4o",
        "ChromaDB",
        "MongoDB",
        "Docker",
      ],
      github: "",
      demo: "https://discord.com/oauth2/authorize?client_id=1127105994766426122",
      status: "completed" as const,
      date: "2026",
    },
    {
      id: 5,
      title: "CineHub",
      description:
        "Intelligent movie and TV show discovery platform with AI recommendation algorithms using cosine similarity and dual database architecture.",
      image: "/projects/cinehub.png",
      technologies: [
        "React",
        "TypeScript",
        "Node.js",
        "PostgreSQL",
        "MongoDB",
        "Supabase",
        "Tailwind CSS",
      ],
      github: "https://github.com/ezrabrilliant/cinehub",
      demo: "https://pdds.ezrabrilliant.tech",
      status: "completed" as const,
      date: "2025",
    },
    {
      id: 6,
      title: "Bee Furniture CRM",
      description:
        "Comprehensive web-based CRM for a wooden furniture company — 6 modules (customers, products, transactions, promos, tasks, admin) plus an analytics dashboard. Built as an internal admin tool with a team of 3.",
      image: "/projects/Bee.png",
      technologies: [
        "React",
        "TypeScript",
        "Node.js",
        "Express.js",
        "PostgreSQL",
        "Supabase",
        "Docker",
      ],
      github: "https://github.com/ezrabrilliant/manpro",
      demo: "https://manpro.ezrabrilliant.tech",
      status: "completed" as const,
      date: "2025",
    },
    {
      id: 7,
      title: "PeduliPasal",
      description:
        "AI-powered Android app to assist lawyers and law students in navigating Indonesian legal statutes using TensorFlow and Gemini API.",
      image: "/projects/PeduliPasal.png",
      technologies: [
        "Android",
        "Kotlin",
        "TensorFlow",
        "Gemini API",
        "Firebase",
        "Flask",
      ],
      github:
        "https://github.com/aliefauzan/Bangkit-Project-PeduliPasal",
      demo: "https://github.com/aliefauzan/Bangkit-Project-PeduliPasal/releases/tag/1.5.3",
      status: "completed" as const,
      date: "2024 – 2025",
    },
    {
      id: 8,
      title: "DL Price Prediction",
      description:
        "ML system for Growtopia Diamond Lock prices — scrapes historical price posts from Discord, cleans and structures them, and trains an LSTM time-series model to forecast price movement, with candlestick charts and trend insight.",
      image: "/projects/DL.png",
      technologies: [
        "Python",
        "LSTM",
        "Discord.py",
        "Pandas",
        "MongoDB",
        "Matplotlib",
      ],
      github: "https://github.com/ezrabrilliant/collect-price-dl",
      demo: "",
      status: "completed" as const,
      date: "2026",
    },
    {
      id: 9,
      title: "Orbit Store",
      description:
        "In-Discord commerce bot with real QRIS payment processing through Midtrans API — automates order handling and payment generation with customer & product records. Processed 2,700+ orders from 370+ unique buyers.",
      image: "/projects/QRIS.png",
      technologies: [
        "Discord.js",
        "MongoDB",
        "Midtrans API",
        "QRIS",
        "Node.js",
        "Express.js",
      ],
      github: "",
      demo: "",
      status: "completed" as const,
      date: "2024",
    },
    {
      id: 10,
      title: "PawCare",
      description:
        "Pet shop management system with service ordering, delivery tracking via Google Maps, and multi-role dashboards.",
      image: "/projects/PawCare.png",
      technologies: [
        "Laravel",
        "PHP",
        "MySQL",
        "Google Maps API",
        "JavaScript",
      ],
      github: "https://github.com/ezrabrilliant/pawcare-laravel",
      demo: "https://pawcare.ezrabrilliant.tech",
      status: "completed" as const,
      date: "2024",
    },
    {
      id: 11,
      title: "Portfolio Website",
      description:
        "This site — a personal portfolio centralizing my projects, experience, and education, with a responsive layout, animated UI, and a 96+ PageSpeed score.",
      image: "/projects/Portfolio.png",
      technologies: [
        "React",
        "TypeScript",
        "Tailwind CSS",
        "Framer Motion",
        "Vite",
      ],
      github: "https://github.com/ezrabrilliant/portfolio",
      demo: "https://ezrabrilliant.com",
      status: "completed" as const,
      date: "2026",
    },
    {
      id: 12,
      title: "Pay2Win",
      description:
        "Game top-up website with user authentication, balance management, and payment processing built with vanilla PHP.",
      image: "/projects/Pay2Win.png",
      technologies: ["PHP", "JavaScript", "MySQL", "Bootstrap", "AJAX"],
      github: "https://github.com/ezrabrilliant/project-tekweb",
      demo: "https://pay2win.ezrabrilliant.tech",
      status: "completed" as const,
      date: "2023",
    },
  ],

  skills: [
    {
      category: "Frontend",
      items: [
        "React",
        "TypeScript",
        "Next.js",
        "Tailwind CSS",
        "JavaScript",
      ],
    },
    {
      category: "Mobile",
      items: ["Android", "Kotlin", "Flutter", "Dart", "Firebase"],
    },
    {
      category: "Backend",
      items: [
        "Node.js",
        "Express.js",
        "Discord.js",
        "PostgreSQL",
        "MongoDB",
        "Prisma",
      ],
    },
    {
      category: "Payment & APIs",
      items: [
        "Midtrans API",
        "QRIS",
        "Webhooks",
        "REST API",
        "Payment Gateway",
      ],
    },
    {
      category: "Data & BI",
      items: ["Power BI", "Tableau", "SQL", "Excel", "Python"],
    },
    {
      category: "Tools",
      items: ["Git", "VS Code", "Figma", "Postman", "Linux", "Docker"],
    },
  ],
} as const;

export type Config = typeof config;
